/* ----------------------
   WNNMENU.H header file
   ---------------------- */
   
#define WNNM_NEW                1
#define WNNM_OPEN               2
#define WNNM_SAVE               3
#define WNNM_SAVEAS             4
#define WNNM_EXIT               5

#define WNNM_UNDO              10
#define WNNM_CUT               11
#define WNNM_COPY              12
#define WNNM_PASTE             13
#define WNNM_DEL               14

#define WNNM_WEIGHTS           20
#define WNNM_STEP              21
#define WNNM_CYCLE             22
#define WNNM_TRAININGSET       23
#define WNNM_ENVIRONMENT       24
#define WNNM_VARIABLES         25
#define WNNM_GRAPHICS          26

#define WNNM_ABOUT            100
